basePath: /api/v1
definitions:
  handlers.User:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: phanorcoll@gmail.com
    name: Phanor Coll
    url: https://www.phanorcoll.com
  description: Todo application implementing CharmKV(Badger) as database
  title: Todo Badger (Name will Change)
  version: "1.0"
paths:
  /users:
    get:
      consumes:
      - application/json
      description: Gets the list of users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.User'
      summary: List the users in the system
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Creates a new user
      parameters:
      - description: Create User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/handlers.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.User'
      summary: Creates a new user in the system
      tags:
      - users
swagger: "2.0"
